### ISSUE TITLE
TypeError: Cannot read property 'bind' of undefined

### ISSUE THREAD

**Issue by Sanic** [PavelVanecek/hubot-cronjob#3]
Thanks for developing this hubot package!

I downloaded it today for the very first time and wanted to create the following toy example:

```
HubotCron = require 'hubot-cronjob'

module.exports = (robot) ->
  # monday to friday, 11am
  pattern = '0 11 * * 1-5'
  timezone = 'Europe/Berlin'
  fn = ->
    robot.messageRoom 'testing', "Hey guys!"
  new HubotCron pattern, timezone, fn
```

But this throws the following error:

```
[Tue Sep 06 2016 12:53:16 GMT+0200 (CEST)] ERROR Error loading scripts from npm package - TypeError: Cannot read property 'bind' of undefined
  at HubotCron (/home/hubot/bot/node_modules/hubot-cronjob/src/cronjob.coffee:11:20, <js>:12:59)
  at Robot.loadExternalScripts (/home/hubot/bot/node_modules/hubot/src/robot.coffee:401:11, <js>:272:39)
  at /home/hubot/bot/node_modules/hubot/bin/hubot:152:11, <js>:159:26
  at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:445:3)

```

Any ideas on fixing this?

**Comment by PavelVanecek** [comment]
Hi, so I just tried to copy paste this and it works well for me. Can you post version of node, coffee-script, hubot, and hubot-cronjob you are using? Also, is this OSX or Linux or Windows? Maybe the full project source would help so I can reproduce the error.

**Comment by srstsavage** [comment]
I'm seeing this also.

node = 5.12.0
coffee = 1.6.3
hubot = 2.19.0
hubot-cronjob = 0.2.2

This is inside a Docker image ([phusion baseimage 0.9.18](https://github.com/phusion/baseimage-docker/tree/rel-0.9.18), which is based on Ubuntu 14.04 LTS).

**Comment by srstsavage** [comment]
Any ideas here?

**Comment by PavelVanecek** [comment]
Cannot reproduce: https://github.com/PavelVanecek/hubot-cronjob-issue3-troubleshooting

Running both on host and in a container works for me. If you show me the failing code I can see what is wrong, until then: no ideas.

**Comment by MrTrustor** [comment]
I had the same issue because I had listed "hubot-cronjob" in the ``external-scripts.json`` file. Removing it solved the problem.

**Comment by Sanic** [comment]
Thanks @MrTrustor !
That fixes the problem :)
